# File modes.
O_RDONLY = 0
O_WRONLY = 01
O_RDWR   = 02
O_CREAT  = 0100
O_EXCL   = 0200
O_TRUNC  = 01000

# Access modes 
FA_WRITE = 'w'
FA_READ = 'r'
FA_WRITEBIN = 'wb'
FA_READBIN = 'rb'

# Values for attr->type.
SSH_FILEXFER_TYPE_REGULAR = 1
SSH_FILEXFER_TYPE_DIRECTORY = 2
SSH_FILEXFER_TYPE_SYMLINK = 3
SSH_FILEXFER_TYPE_SPECIAL = 4
SSH_FILEXFER_TYPE_UNKNOWN = 5

