# File modes.
O_RDONLY = 0o0
O_WRONLY = 0o1
O_RDWR   = 0o2
O_CREAT  = 0o100
O_EXCL   = 0o200
O_TRUNC  = 0o1000

# Access modes 
FA_WRITE = 'w'
FA_READ = 'r'
FA_WRITEBIN = 'wb'
FA_READBIN = 'rb'

# Values for attr->type.
SSH_FILEXFER_TYPE_REGULAR = 1
SSH_FILEXFER_TYPE_DIRECTORY = 2
SSH_FILEXFER_TYPE_SYMLINK = 3
SSH_FILEXFER_TYPE_SPECIAL = 4
SSH_FILEXFER_TYPE_UNKNOWN = 5

